
AWSTemplateFormatVersion: '2010-09-09'

Description: 'Cloud Formation to EC2 Instances to Install Oracle Database'

################################################################################
#                                Parameters                                    #
################################################################################
Parameters:
  VPCID:
    Description: VPCID
    Type: String
  Subnet01:
    Description: Subnet ID
    Type: String
  VPCIDR:
    Description: VPC CIDR Range
    Type: String
  KeyPairName:
    Description: Key Pair Name
    Type: String

################################################################################
#                                  Mappings                                    #
################################################################################
Mappings:
  LinuxEC2:
    sa-east-1:
      HVM64: ami-01fc9174dd9330556

################################################################################
#                                  Resources                                   #
################################################################################
Resources:

  #################################### SG ######################################
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security Group for Bastion Host"
      GroupName: SGBastion
      VpcId: !Ref VPCID
      SecurityGroupIngress: 
        - CidrIp: !Ref VPCIDR
          FromPort: 443
          IpProtocol: "tcp"
          ToPort: 443

  ################################### EC2 ####################################
  EC2Linux:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref EC2ServerInstanceProfile
      InstanceType: t3.micro
      KeyName: !Ref KeyPairName
      # SubnetId: {'Fn::ImportValue':  "VPC-outTestPubSubnet01"}
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !GetAtt EC2SecurityGroup.GroupId
          # SubnetId: {'Fn::ImportValue':  "VPC-outTestPubSubnet01"}  
          SubnetId: !Ref Subnet01
            # Ref: "PublicSubnet"
      ImageId: !FindInMap
        - LinuxEC2
        - !Ref "AWS::Region"
        - HVM64
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
      UserData:
        'Fn::Base64':
          !Sub |
            #!/bin/bash
            yum update -y
            yum install unzip
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

            
  ################################### IAM ####################################
  SSMIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: 'S3-Access'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 
                  - s3:ListAllMyBuckets
                Resource: '*'
              - Effect: 'Allow'
                Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:GetBucketACL
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  - Fn::ImportValue: S3BucketARN
                  # - !GetAtt S3Bucket.Arn

  EC2ServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref SSMIAMRole
